# Generated by Django 4.1.6 on 2023-03-16 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date',
            field=models.DateField(default='1993-03-5'),
            preserve_default=False,
        ),
    ]
